// <auto-generated />
using System;
using FacultyApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FacultyApp.Migrations
{
    [DbContext(typeof(StudentsDbContext))]
    [Migration("20240424121424_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FacultyApp.Model.Course", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeacherId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = "8e120241-2e9b-43f4-b315-50418fb52c46",
                            Department = "Computer Science",
                            Name = "Introduction to Programming",
                            TeacherId = "1",
                            Year = 1
                        },
                        new
                        {
                            Id = "cf10cc98-e2fe-4f91-8a59-5a7e97bd142e",
                            Department = "Computer Science",
                            Name = "Data Structures and Algorithms",
                            TeacherId = "1",
                            Year = 2
                        },
                        new
                        {
                            Id = "b023ea15-4558-40c0-890c-e459d1d5f95f",
                            Department = "Databases",
                            Name = "Database Management Systems",
                            TeacherId = "2",
                            Year = 3
                        });
                });

            modelBuilder.Entity("FacultyApp.Model.Examination", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("CourseId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Examinations");
                });

            modelBuilder.Entity("FacultyApp.Model.Student", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<int>("CurrentYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EnrolledIn")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("GPA")
                        .HasColumnType("real");

                    b.Property<bool>("Graduated")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = "7648ce32-e260-4614-b301-b51d3e09cfa6",
                            CurrentYear = 3,
                            DateOfBirth = new DateTime(1995, 5, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alicesmith@gmail.com",
                            EnrolledIn = 2021L,
                            FirstName = "Alice",
                            GPA = 8.5f,
                            Graduated = false,
                            LastName = "Smith",
                            Password = "D7BEEAF7D6E5067747D6E412887DDDE01BB7A7784273C459B208A9899BE9C377584A9FA4767748A00A103E6D2942EB4BC6533BCA9804D833F2BD074BC4B0A9AD"
                        },
                        new
                        {
                            Id = "ccb15ded-b5ee-4f0c-a7dc-fee6aeb878eb",
                            CurrentYear = 4,
                            DateOfBirth = new DateTime(1998, 9, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bobjohnson@gmail.com",
                            EnrolledIn = 2020L,
                            FirstName = "Bob",
                            GPA = 9.2f,
                            Graduated = false,
                            LastName = "Johnson",
                            Password = "D7BEEAF7D6E5067747D6E412887DDDE01BB7A7784273C459B208A9899BE9C377584A9FA4767748A00A103E6D2942EB4BC6533BCA9804D833F2BD074BC4B0A9AD"
                        });
                });

            modelBuilder.Entity("FacultyApp.Model.Teacher", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("EmployedIn")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            DateOfBirth = new DateTime(1978, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Computer Science",
                            Email = "johndoe@gmail.com",
                            EmployedIn = 2010L,
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "D7BEEAF7D6E5067747D6E412887DDDE01BB7A7784273C459B208A9899BE9C377584A9FA4767748A00A103E6D2942EB4BC6533BCA9804D833F2BD074BC4B0A9AD"
                        },
                        new
                        {
                            Id = "2",
                            DateOfBirth = new DateTime(1985, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Databases",
                            Email = "janedoe@gmail.com",
                            EmployedIn = 2012L,
                            FirstName = "Jane",
                            LastName = "Doe",
                            Password = "D7BEEAF7D6E5067747D6E412887DDDE01BB7A7784273C459B208A9899BE9C377584A9FA4767748A00A103E6D2942EB4BC6533BCA9804D833F2BD074BC4B0A9AD"
                        });
                });

            modelBuilder.Entity("FacultyApp.Model.Course", b =>
                {
                    b.HasOne("FacultyApp.Model.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("FacultyApp.Model.Examination", b =>
                {
                    b.HasOne("FacultyApp.Model.Course", null)
                        .WithMany("Examinations")
                        .HasForeignKey("CourseId");
                });

            modelBuilder.Entity("FacultyApp.Model.Course", b =>
                {
                    b.Navigation("Examinations");
                });
#pragma warning restore 612, 618
        }
    }
}
